# 来自：https://github.com/ouuan/ouuan/blob/master/.github/workflows/topFollowers.yml
name: Get Top Followers

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  top-followers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
      - name: Install requests
        run: pip install requests
      - name: Update README
        run: python src/getTopFollowers.py ${{ github.repository_owner }} ${{ secrets.GITHUB_TOKEN }} README.md
      - name: Commit changes
        run: |
          git config --local user.email "chinagodman1@gmail.com"
          git config --local user.name "ChinaGodBot"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Update top followers"
      - name: Pull changes
        run: git pull -r
      - name: Push changes
        uses: ad-m/github-push-action@d91a481090679876dfc4178fef17f286781251df
        with:
          github_token: ${{ secrets.TOKEN }}
