name: WakaTime status update

on:
  schedule:
    - cron: "0 4 * * *" # UTC+8 上午 12:00 运行一次
  workflow_dispatch:

jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest
    steps:
      - uses: avinal/Profile-Readme-WakaTime@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BRANCH: "main"
          COMMIT_MSG: "chore: update coding activity update"
